# Generated by Django 4.2.7 on 2023-11-10 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 13 digits only!', regex='^\\d{10}')])),
                ('user_type', models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], max_length=20)),
                ('seller_type', models.CharField(blank=True, choices=[('farmer', 'Farmer'), ('private_business', 'Private Business')], max_length=20, null=True)),
                ('buyer_type', models.CharField(blank=True, choices=[('consumer', 'Consumer'), ('private_business', 'Private Business')], max_length=20, null=True)),
            ],
        ),
    ]
